package com.ccdp.appakhir2;


import android.os.Bundle;
import android.support.v4.app.Fragment;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.webkit.WebView;


/**
 * A simple {@link Fragment} subclass.
 */
public class Bahaya extends Fragment {


    public Bahaya() {
        // Required empty public constructor
    }


    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        View rootView = inflater.inflate(R.layout.fragment_bahaya,
                container, false);
        WebView view = (WebView) rootView.findViewById(R.id.bahaya1);
        String text =
                "<p align=\"justify\">Filosofi \"penyelamatan dengan biaya apapun\" dari konflik sebelumnya tidak mungkin terjadi dalam konflik di masa depan. Musuh potensial kami telah membuat kemajuan besar dalam tindakan pertahanan udara dan teknik pencarian arah radio (RDF). Kita harus berasumsi bahwa pasukan militer A.S. yang terjebak di belakang garis musuh dalam konflik di masa depan mungkin tidak mengalami pemulihan cepat dengan elemen ramah. Tentara mungkin harus bergerak untuk waktu dan jarak yang jauh ke tempat-tempat yang tidak terlalu mengancam kekuatan pemulihan. Prajurit itu sepertinya tidak akan tahu jenis pemulihan yang diharapkannya. Setiap situasi dan sumber daya yang tersedia menentukan jenis kemungkinan pemulihan. Karena tidak ada yang bisa benar-benar yakin sampai usaha pemulihan dimulai, tentara yang menghadapi potensi cutoff dari pasukan ramah harus terbiasa dengan semua jenis pemulihan yang mungkin, masalah terkait mereka, dan tanggung jawab mereka terhadap upaya pemulihan. Persiapan dan latihan bisa meningkatkan peluang sukses.<br>" +
                "<p align=\"center\"><b>FASE PERENCANAAN</b><br>" +
                "<p align=\"justify\">Persiapan adalah persyaratan untuk semua misi. Saat merencanakan, Anda harus mempertimbangkan bagaimana cara menghindari penangkapan dan kembali ke unit Anda. Rencana kontingensi harus disiapkan bersamaan dengan unit standing operating procedures (SOPs). Tindakan yang Anda atau unit Anda lakukan juga harus dipertimbangkan.<br>" +
                " <br><b>Contingency Plan of Action (CPA)</b> <br>" +
                "Bagian intelijen dapat membantu mempersiapkan personil untuk tindakan kontingensi melalui informasi yang diberikan di bidang studi, SERE (survival, evasion, resistance, and escape) panduan kontingensi, briefing ancaman, laporan intelijen terkini, dan prosedur kontak dan otentikasi terkini. Persiapan pra-misi mencakup penyelesaian CPA. Penelitian dan penelitian yang dibutuhkan untuk mengembangkan CPA akan membuat Anda sadar akan situasi saat ini di wilayah misi Anda. CPA Anda akan membiarkan kekuatan pemulihan mengetahui kemungkinan tindakan Anda jika Anda harus pindah untuk menghindari penangkapan.<br>" +
                " <br>Mulai siapkan bahkan sebelum perencanaan pra-misi. Banyak bagian CPA adalah SOP untuk unit Anda. Sertakan CPA dalam pelatihan Anda. Perencanaan dimulai pada pelatihan harian Anda.<br>" +
                " <br>CPA adalah keseluruhan rencana Anda untuk kembali ke kontrol ramah. Ini terdiri dari lima paragraf yang ditulis dalam format perintah operasi. Anda dapat mengambil sebagian besar ayat 1, Situasi, dengan Anda dalam misi tersebut. Lampiran H berisi format BPA. Ini juga menunjukkan bagian BPA mana yang dapat Anda bawa.<br>" +
                " <br>CPA komprehensif adalah aset berharga bagi tentara yang terjebak di balik garis musuh yang harus berusaha menghindari penangkapan. Untuk melengkapi paragraf 1, ketahui area yang ditugaskan oleh unit Anda atau berkonsentrasilah pada area misi potensial di dunia. Banyak sumber terbuka atau tertutup berisi informasi yang Anda butuhkan untuk menyelesaikan CPA. Sumber terbuka dapat mencakup surat kabar, majalah, buku pegangan negara atau wilayah, studi wilayah, televisi, radio, orang-orang yang mengenal area, dan perpustakaan. Sumber-sumber yang tertutup mungkin termasuk studi wilayah, penilaian wilayah, panduan kontingensi SERE, berbagai manual lapangan yang diklasifikasikan, dan laporan intelijen.<br>" +
                " <br>Siapkan CPA Anda dalam tiga tahap. Selama latihan normal Anda, siapkan paragraf 1, Situasi. Siapkan paragraf 2, 3, 4, dan 5 selama perencanaan pra-misi Anda. Setelah melakukan penyebaran ke suatu wilayah, terus perbarui CPA Anda berdasarkan perubahan misi dan pembaruan intelijen.<br>" +
                " <br>CPA adalah panduan. Anda dapat menambahkan atau menghapus bagian tertentu berdasarkan misi. CPA mungkin merupakan alat pemulihan hanya untuk menentukan lokasi dan niat Anda setelah Anda mulai bergerak. Ini adalah alat penting untuk kelangsungan hidup Anda dan kembali ke kontrol yang ramah.<br>" +
                " <br><b>Standing Operating Procedures</b><br>" +
                "Unit SOP adalah alat berharga yang dimiliki unit Anda yang akan membantu perencanaan Anda. Bila dihadapkan pada situasi berbahaya yang membutuhkan tindakan segera, sekarang bukan waktunya untuk mendiskusikan pilihan; inilah saatnya bertindak. Banyak teknik yang digunakan selama pergerakan unit kecil dapat dilakukan sesuai persyaratan untuk bergerak dan kembali ke kontrol ramah. Item dari SOP harus mencakup, namun tidak terbatas pada--<br><br>" +
                "<ul><li>Ukuran pergerakan tim (tiga sampai empat orang per tim). <br>" +
                "<li>Komunikasi antar anggota tim (teknikal dan nonteknikal). <br>" +
                "<li>Perlengkapan penting. <br>" +
                "<li>Tindakan di daerah berbahaya. <br>" +
                "<li>Teknik pensinyalan. <br>" +
                "<li>Latihan tindakan segera. <br>" +
                "<li>Perangkat dan prosedur pemulihan helikopter.<br>" +
                "<li>Prosedur keamanan selama gerakan dan di tempat persembunyian.<br>" +
                "<li>Titik temu. <br>" +
                "</ul><p align=\"justify\">Latihan bekerja efektif untuk memperkuat keterampilan SOP ini dan juga memberi kesempatan untuk evaluasi dan perbaikan.<br>" +
                " <br>Pemberitahuan untuk Bergerak dan Menghindari Penangkapan<br>" +
                " <br>Unit yang terisolasi memiliki beberapa tindakan umum yang dapat dilakukan untuk menghindari penangkapan kelompok atau individu. Kursus tindakan ini bukan kursus yang bisa dipilih komandan daripada misi awalnya. Dia tidak bisa secara sembarangan meninggalkan misi yang ditugaskan. Sebaliknya, dia mungkin akan mengadopsi tindakan ini setelah menyelesaikan misinya ketika unitnya tidak dapat menyelesaikan misi yang ditugaskannya (karena kerugian kekuatan tempur) atau saat dia menerima pesanan untuk mengambil unitnya dari posisi saat ini. Jika tindakan semacam itu tidak memungkinkan, komandan dapat memutuskan agar unit tersebut mencoba bergerak untuk menghindari penangkapan dan kembali ke kontrol ramah. Dalam kedua kasus tersebut, selama ada komunikasi dengan kantor pusat yang lebih tinggi, kantor pusat tersebut akan mengambil keputusan.<br>" +
                " <br>Jika komandan unit kehilangan kontak dengan kantor pusat yang lebih tinggi, dia harus membuat keputusan untuk pindah atau menunggu. Dia mendasarkan keputusannya pada banyak faktor, termasuk misi, jatah dan amunisi di tangan, korban jiwa, kesempatan untuk melegakan oleh kekuatan ramah, dan situasi taktis. Komandan unit yang terisolasi menghadapi pertanyaan lain. Tindakan apa yang akan menyebabkan kerusakan maksimal pada musuh? Tindakan apa yang akan membantu menyelesaikan misi keseluruhan kantor pusat yang lebih tinggi?<br>" +
                "<br>" +
                "Tim gerakan melakukan bagian pelaksanaan rencana saat diberitahu oleh kantor pusat yang lebih tinggi atau, jika tidak ada kontak dengan kantor pusat yang lebih tinggi, saat korban peringkat tertinggi memutuskan bahwa situasi mengharuskan unit tersebut untuk melarikan diri dari penangkapan atau penghancuran. Pemimpin tim gerakan menerima pemberitahuan mereka melalui sinyal prebriefed. Begitu sinyal untuk mencoba menghindari penangkapan diberikan, maka harus dilalui dengan cepat ke semua personil. Beritahu kantor pusat yang lebih tinggi, jika memungkinkan. Jika tidak dapat berkomunikasi dengan kantor pusat yang lebih tinggi, para pemimpin harus menyadari bahwa perlawanan terorganisir telah berakhir, dan kontrol organisasi telah berhenti. Komando dan kontrol sekarang berada di tim gerakan atau tingkat individu dan dikembalikan ke kontrol organisasi yang lebih tinggi hanya setelah mencapai jalur aman.<br>" +
                "<p align=\"center\"><b>EKSEKUSI</b><br>" +
                "<p align=\"justify\">Setelah pemberitahuan untuk menghindari penangkapan, semua anggota tim pergerakan akan mencoba untuk menghubungkan titik awal gerakan tersebut. Poin ini adalah dimana anggota tim rally dan benar-benar memulai gerakan mereka. Secara tentatif pilih titik pergerakan awal selama tahap perencanaan Anda melalui rekon peta. Begitu berada di lapangan, tim memverifikasi lokasi ini atau memilih yang lebih baik. Semua anggota tim harus tahu lokasinya. Titik pergerakan awal harus mudah ditemukan dan menempati waktu minimum.<br>" +
                "<br>" +
                "Begitu tim telah berkumpul pada titik pergerakan awal, harus --<br>" +
                "<ul><li>Berikan pertolongan pertama.<br>" +
                "<li>Persediaan peralatannya (putuskan apa yang harus ditinggalkan, hancurkan, atau bawa bersama).<br>" +
                "<li>Terapkan kamuflase.<br>" +
                "<li>Pastikan semua orang mengetahui lokasi persembunyian tentatif.<br>" +
                "<li>Pastikan semua orang mengetahui rute utama dan alternatif serta titik rawan dalam perjalanan menuju lokasi yang tersembunyi.<br>" +
                "<li>Selalu menjaga keamanan.<br>" +
                "<li>Pisahkan tim menjadi elemen yang lebih kecil. Yang ideal<br>" +
                "</ul><p align=\"justify\">Elemen harus memiliki dua sampai tiga anggota; Namun, itu bisa mencakup lebih banyak tergantung pada peralatan dan pengalaman tim.<br>" +
                "<br>" +
                "Bagian pergerakan kembali ke kontrol ramah adalah yang paling berbahaya karena Anda sekarang paling rentan. Biasanya lebih baik bergerak di malam hari karena kegelapan disembunyikan menawarkan. Pengecualian untuk gerakan seperti itu adalah saat bergerak melalui medan berbahaya atau vegetasi padat (misalnya, kawasan hutan atau pegunungan).<br>" +
                " <br>Saat bergerak, hindari hal berikut meski membutuhkan lebih banyak waktu dan energi untuk memotong:<br>" +
                "<ul><li>Kendala dan rintangan.<br>" +
                "<li>Jalan dan jalan setapak.<br>" +
                "<li>daerah yang dihuni<br>" +
                "<li>Jalan air dan jembatan.<br>" +
                "<li>Garis melayang alami.<br>" +
                "<li>Struktur buatan manusia.<br>" +
                "<li>Semua personil sipil dan militer.<br>" +
                "</ul><br>" +
                "<p align=\"justify\">Gerakan di wilayah yang dilanda musuh adalah proses yang sangat lambat dan disengaja. Semakin lambat Anda bergerak dan semakin berhati-hati Anda, semakin baik. Keamanan terbaik Anda akan menggunakan indra Anda. Gunakan mata dan telinga Anda untuk mendeteksi orang sebelum mereka mendeteksi Anda. Sering-seringlah menyimak. Di siang hari, amati bagian dari rute Anda sebelum Anda bergerak melewatinya. Jarak yang Anda tempuh sebelum bersembunyi akan tergantung pada situasi musuh, kesehatan, medan, ketersediaan penutup dan penyembunyian untuk bersembunyi, dan jumlah kegelapan yang tersisa.<br>" +
                "<br>" +
                "<b>Sembunyikan Aktivitas Situs</b><br>" +
                "Setelah Anda menemukan situs tersembunyi Anda, jangan langsung bergerak ke dalamnya. Gunakan kancing tombol atau teknik menipu lainnya untuk berpindah ke posisi di luar tempat persembunyian. Lakukan pendengaran sebelum berhenti secara pribadi ke tempat persembunyian. Hati-hati jangan sampai mengganggu atau memotong vegetasi apapun. Setelah Anda menempati situs persembunyian, batasi aktivitas Anda untuk menjaga keamanan, beristirahat, menyamarkan, dan merencanakan langkah selanjutnya.<br>" +
                " <br>Pertahankan keamanan Anda melalui pemindaian visual dan pendengaran. Setelah mendeteksi musuh, petugas keamanan mengingatkan semua personil, bahkan jika rencana tim tersebut tetap tersembunyi dan tidak bergerak saat melihat musuh. Ambil tindakan ini agar setiap orang sadar akan bahaya dan siap bereaksi.<br>" +
                "<br>" +
                "Jika ada anggota tim yang meninggalkan tim, beri dia rencana kontingensi lima poin. Lakukan langkah-langkah seperti itu terutama saat tim rekam atau partai kerja keluar dari lubang atau sembunyikan situs.<br>" +
                "<br>" +
                "Hal ini sangat penting untuk tetap sehat dan waspada saat mencoba menghindari penangkapan. Ambillah setiap kesempatan untuk beristirahat, tapi jangan mengorbankan keamanan. Putar keamanan sehingga semua anggota tim gerakan Anda bisa beristirahat. Perlakukan semua luka, tidak peduli seberapa kecil. Hilangnya kesehatan Anda akan berarti kehilangan kemampuan Anda untuk terus menghindari penangkapan.<br>" +
                "<br>" +
                "Kamuflase adalah aspek penting dari keduanya bergerak dan mengamankan tempat persembunyian. Selalu gunakan sistem sobat untuk memastikan kamuflase selesai. Pastikan anggota tim berbaur dengan situs sembunyi. Gunakan bahan alami atau buatan manusia. Jika Anda menambahkan bahan penyamaran tambahan ke tempat persembunyian, jangan memotong vegetasi di daerah sekitar.<br>" +
                " <br>Rencanakan tindakan Anda selanjutnya saat berada di tempat persembunyian. Mulailah proses perencanaan Anda segera setelah menempati situs yang disembunyikan. Informasikan kepada semua anggota tim lokasi mereka saat ini dan sebutkan lokasi persembunyian alternatif. Setelah ini selesai, mulailah merencanakan gerakan berikutnya tim.<br>" +
                "<br>" +
                "Merencanakan gerakan tim dimulai dengan rekonstruksi peta. Pilih area hide berikutnya terlebih dahulu. Kemudian pilih rute primer dan alternatif ke area tersembunyi. Dalam memilih rute, jangan gunakan garis lurus. Gunakan satu atau dua perubahan radikal dalam arah. Pilih rute yang menawarkan penutup dan penyembunyian terbaik, hambatan paling sedikit, dan kemungkinan kontak dengan manusia paling sedikit. Harus ada lokasi di sepanjang rute dimana tim bisa mendapatkan air. Untuk membantu navigasi tim, gunakan azimuth, jarak, titik pemeriksaan atau tanda kemudi, dan koridor. Rencanakan poin rally dan titik pertemuan pada interval sepanjang rute.<br>" +
                "<br>" +
                "Pertimbangan perencanaan lainnya mungkin termasuk dalam tim yang telah ada dalam tim SOP. Contohnya adalah latihan tindakan segera, tindakan untuk melihat musuh, dan sinyal tangan dan lengan.<br>" +
                "<br>" +
                "Setelah perencanaan selesai, pastikan semua orang mengetahui dan menghafal keseluruhan rencana. Anggota tim harus mengetahui jarak dan azimuth untuk keseluruhan rute ke area persembunyian berikutnya. Mereka harus mempelajari peta dan mengetahui berbagai medan yang akan mereka pindahkan sehingga bisa bergerak tanpa menggunakan peta.<br>" +
                " <br>Jangan menempati situs sembunyi selama lebih dari 24 jam. Dalam kebanyakan situasi, sembunyikan di siang hari dan bergeraklah di malam hari. Batasi tindakan Anda di situs yang disembunyikan dengan yang dibahas di atas. Begitu di tempat persembunyian, batasi semua gerakan kurang dari 45 sentimeter di atas tanah. Jangan membangun api atau menyiapkan makanan. Bau asap dan makanan akan mengungkapkan lokasi Anda. Sebelum meninggalkan situs sembunyi, sterilkan untuk mencegah pelacakan.<br>" +
                " <b><br>Hole-Up Areas</b> <br>" +
                "Setelah bergerak dan bersembunyi selama beberapa hari, biasanya tiga atau empat, Anda atau tim gerakan harus pindah ke area lubang. Ini adalah area di mana Anda bisa beristirahat, memulihkan kesehatan, dan mendapatkan dan menyiapkan makanan. Pilih area di dekat sumber air. Anda kemudian memiliki tempat untuk mendapatkan air, untuk menempatkan perangkat memancing, dan untuk menjebak permainan. Karena jalur air adalah jalur komunikasi, cari tempat persembunyian Anda jauh dari air.<br>" +
                "<br>" +
                "Area lubang-lubang harus menawarkan banyak penutup dan penyembunyian untuk pergerakan di dalam dan sekitar area. Selalu menjaga keamanan saat berada di area hole-up. Selalu manusia daerah hole-up. Tindakan di area lubang-lubang sama seperti di tempat persembunyian, kecuali bahwa Anda bisa menjauh dari area lubang-lubang untuk mendapatkan dan menyiapkan makanan. Tindakan di daerah lubang-lubang meliputi -<br>" +
                "<ul><li>Memilih dan menempati situs persembunyian berikutnya (ingat Anda masih berada dalam situasi yang berbahaya; ini bukan area yang ramah).</li>" +
                "<li>Rekonstruksi area untuk sumber daya dan jalur pergerakan tersembunyi yang potensial ke situs persembunyian alternatif.</li>" +
                "<li>Mengumpulkan makanan (kacang-kacangan, buah beri, sayuran). Saat bergerak di sekitar area makanan, pertahankan keamanan dan hindari meninggalkan jejak atau tanda lainnya. Saat memasang perangkap dan perangkap, jagalah agar tetap terhubung dengan baik dan di daerah di mana orang tidak mungkin menemukannya. Ingat, penduduk lokal kadang-kadang dengan berat menempuh jalan setapak di dekat sumber air.</li>" +
                "<li>Mendapatkan air dari sumber di area sembunyi. Hati-hati jangan sampai meninggalkan jejak tanda di sepanjang tepi sumber air saat mendapatkan air. Bergerak di atas batu keras atau kayu bulat di sepanjang tepi sungai untuk mendapatkan air akan mengurangi tanda-tanda yang Anda tinggalkan.</li>" +
                "<li>Menetapkan perangkat memancing klandestin, seperti pengintaian, di bawah permukaan air untuk menghindari deteksi.</li>" +
                "<li>Menemukan lokasi pemadam kebakaran jauh dari tempat persembunyian. Gunakan situs ini untuk menyiapkan makanan atau air mendidih. Kamuflase dan mensterilkan api dari setiap penggunaan. Hati-hati bahwa asap dan cahaya dari api tidak mengganggu area lubang.</li>" +
                "</ul><br>" +
                "<p align=\"justify\">Sementara di area pit-up, keamanan masih menjadi perhatian utama Anda. Tunjuk anggota tim untuk melakukan tugas tertentu. Untuk membatasi pergerakan di sekitar area, Anda mungkin memiliki tim dua orang yang melakukan lebih dari satu tugas. Misalnya, tim yang mendapatkan air juga bisa mengatur alat pancing. Jangan menempati area lubang lebih dari 72 jam. <br>" +
                "<p align=\"center\"><b>KEMBALI KE PENGAWASAN SEKUTU</b><br>" +
                "<p align=\"justify\">Membentuk kontak dengan jalur ramah atau patroli adalah bagian gerakan yang paling penting dan kembali ke kontrol yang ramah. Semua kesabaran, perencanaan, dan kesulitan Anda akan sia-sia jika Anda tidak berhati-hati saat menghubungi pasukan garis depan yang ramah. Patroli yang ramah telah membunuh personil yang beroperasi di belakang garis musuh karena mereka tidak melakukan kontak dengan benar. Sebagian besar korban bisa dihindari jika kehati-hatian telah dilakukan dan beberapa prosedur sederhana diikuti. Kecenderungan normal adalah membuang hati-hati ke angin saat melihat kekuatan ramah. Anda harus mengatasi kecenderungan ini dan memahami bahwa hubungan adalah situasi yang sangat sensitif.<br>" +
                " <br><b>Melintasi Perbatasan</b> <br>" +
                "Jika Anda telah membuat jalan ke negara yang sekutu atau netral, gunakan prosedur berikut untuk melewati perbatasan dan terhubung dengan kekuatan sekutu di sisi lain:<br>" +
                "<ul><li>Menempati tempat persembunyian di sisi dekat perbatasan dan mengirim tim untuk mengintip lokasi persimpangan potensial.</li>" +
                "<li>Surveilasikan lokasi persimpangan minimal 24 jam, tergantung situasi musuh.</li>" +
                "<li>Buat sketsa situs, perhatikan medan, rintangan, rutinitas dan rotasi penjaga, dan perangkat sensor atau kabel perjalanan. Begitu rekon selesai, tim pindah ke tempat persembunyian, memberi tahu tim lainnya, dan berencana untuk melintasi perbatasan pada malam hari.</li>" +
                "<li>Setelah melintasi perbatasan, pasanglah situs tersembunyi di sisi yang jauh dari perbatasan dan cobalah untuk menemukan posisi ramah. Jangan mengungkapkan kehadiran Anda.</li>" +
                "<li>Bergantung pada ukuran tim pergerakan Anda, mintalah dua pria untuk memeriksa lokasi linkase potensial dengan kekuatan ramah sampai puas bahwa personilnya memang ramah.</li>" +
                "<li>Lakukan kontak dengan pasukan yang ramah di siang hari. Personel yang dipilih untuk melakukan kontak harus tidak bersenjata, tidak memiliki peralatan, dan memiliki identifikasi positif yang tersedia. Orang yang benar-benar membuat tautan harus seseorang yang paling mirip dengan musuh.</li>" +
                "<li>Selama kontak sebenarnya, hanya ada satu orang yang melakukan kontak. Orang lain memberikan keamanan dan mengamati area linkup dari jarak yang aman. Pengamat harus cukup jauh sehingga dia bisa memperingatkan anggota tim gerakan lainnya jika terjadi kesalahan.</li>" +
                "<li>Tunggu sampai pesta dia menghubungi terlihat ke arahnya sehingga dia tidak mengejutkan kontaknya. Dia berdiri dari balik penutup, dengan tangan di atas kepala dan menyatakan bahwa dia orang Amerika. Setelah ini, dia mengikuti instruksi yang diberikan kepadanya. Dia menghindari menjawab pertanyaan taktis dan tidak memberi indikasi bahwa ada anggota tim lainnya.</li>" +
                "<li>Mengungkapkan bahwa ada personil lain bersamanya hanya setelah memverifikasi identitasnya dan memuaskan dirinya sendiri bahwa dia telah melakukan kontak dengan pasukan yang ramah.</li>" +
                "</ul><br>" +
                "<p align=\"justify\">Masalah bahasa atau kesulitan untuk mengonfirmasikan identitas mungkin timbul. Tim gerakan harus menjaga keamanan, bersabar, dan memiliki rencana darurat.<br>" +
                "<br>Catatan: Jika Anda pindah ke negara netral, Anda menyerah pada kekuatan itu dan menjadi orang yang ditahan.<br>" +
                " <br><b>Berkomunikasi dengan FEBA/FLOT</b> <br>" +
                "Jika tertangkap antara pasukan yang sekutu dan musuh dan ada pertempuran sengit di daerah itu, Anda dapat memilih untuk bersembunyi dan membiarkan garis ramah melewati Anda. Jika dikuasai oleh pasukan yang ramah, Anda bisa mencoba menghubungkan diri dari belakang saat siang hari. Jika dibanjiri oleh pasukan musuh, Anda bisa bergerak lebih jauh ke belakang musuh, cobalah bergerak ke tepi depan area pertempuran (FEBA) / barisan depan pasukan sendiri (FLOT) saat jeda dalam pertempuran, atau pindah ke area lain. sepanjang bagian depan.<br>" +
                " <br>Tautan yang sebenarnya akan dilakukan seperti untuk penghubung selama persimpangan perbatasan. Satu-satunya perbedaan adalah Anda harus lebih berhati-hati pada kontak awal. Personel garis depan lebih cenderung menembak terlebih dahulu dan mengajukan pertanyaan nanti, terutama di daerah pertempuran berat. Anda harus berada di dekat atau di belakang penutup sebelum mencoba melakukan kontak.<br>" +
                " <b><br>Berkomunikasi Dengan Pasukan Patroli Sekutu </b><br>" +
                "Jika garis ramah adalah lingkaran melingkar atau sebuah kamp yang terisolasi, misalnya, setiap arah yang Anda dekati akan dianggap wilayah musuh. Anda tidak memiliki pilihan untuk bergerak di belakang garis dan mencoba untuk terhubung. Langkah ini membuat linklink sangat berbahaya. Salah satu pilihan yang Anda miliki adalah menempatkan perimeter di bawah pengamatan dan menunggu patroli ramah pindah ke arah Anda, memberi kesempatan untuk melakukan hubungan. Anda mungkin juga menempati posisi di luar batas dan memanggil untuk mendapatkan perhatian dari kekuatan ramah. Idealnya, tampilkan apa saja yang berwarna putih saat melakukan kontak. Jika tidak ada yang lain, gunakan artikel pakaian apa pun. Idenya adalah untuk menarik perhatian sambil tetap di belakang penutup. Setelah Anda menarik perhatian pada sinyal Anda dan berseru, ikuti instruksi yang diberikan kepada Anda.<br>" +
                " <br>Selalu waspada terhadap patroli sekutu karena ini memberi sarana untuk kembali ke kontrol ramah. Temukan posisi tersembunyi yang memungkinkan Anda mendapatkan cakupan visual maksimum di area ini. Cobalah untuk mengingat setiap fitur medan sehingga, jika perlu, Anda bisa menyusup ke posisi ramah di bawah penutup kegelapan. Ingat, mencoba menyusup dalam kegelapan sangat berbahaya.<br>" +
                "<br>Karena misi tempur dan rekonstruksikan patroli dan di mana mereka beroperasi, membuat kontak bisa berbahaya. Jika Anda memutuskan untuk tidak melakukan kontak, Anda dapat mengamati rute mereka dan mendekati jalur ramah di lokasi yang sama. Pengamatan seperti itu akan memungkinkan Anda menghindari ranjau dan jebakan booby.<br>" +
                " <br>Begitu Anda melihat patroli, tetap dalam posisi dan, jika memungkinkan, biarkan patroli bergerak ke arah Anda. Ketika patroli itu 25 sampai 50 meter dari posisi Anda, memberi isyarat mereka dan memanggil ucapan yang jelas dan tidak salah lagi dari asal Amerika.<br>" +
                " <br>Jika Anda tidak memiliki warna putih, artikel pakaian akan cukup menarik perhatian. Jika jaraknya lebih dari 50 meter, patroli rekon bisa menghindari kontak dan melewati posisi Anda. Jika jaraknya kurang dari 25 meter, anggota patroli bisa langsung bereaksi dengan menembakkan tembakan fatal.<br>" +
                " <br>Sangat penting, pada saat kontak, ada cukup cahaya patroli untuk mengidentifikasi Anda sebagai orang Amerika.<br>" +
                " <br>Apapun teknik linkup yang Anda putuskan untuk digunakan, gunakan sangat hati-hati. Dari perspektif patroli ramah atau personil yang ramah yang menempati batas, Anda bermusuhan sampai mereka memberi identifikasi positif.<br>" +
                "<p align=\"center\"><b>SURVIVAL ANCAMAN BAHAYA BUATAN MANUSIA</b><br>";
        String text1 =
                "<p align=\"justify\">" +
                "Senjata nuklir, kimia, dan biologi telah menjadi kenyataan potensial di medan tempur modern manapun. Pengalaman terkini di Afghanistan, Kamboja, dan daerah konflik lainnya telah membuktikan penggunaan senjata kimia dan biologi (seperti mikotoksin). Doktrin perang melawan negara-negara Pakta NATO dan Warsawa membahas penggunaan senjata nuklir dan kimia. Potensi penggunaan senjata ini meningkatkan masalah kelangsungan hidup karena bahaya serius yang ditimbulkan oleh dampak radioaktif atau kontaminasi yang dihasilkan oleh agen biologis atau kimia persisten.<br>" +
                "Anda harus menggunakan tindakan pencegahan khusus jika Anda berharap bertahan dalam bahaya buatan manusia ini. Jika Anda mengalami dampak perang nuklir, kimia, atau biologis, prosedur kelangsungan hidup yang direkomendasikan dalam bab ini dapat menyelamatkan hidup Anda. Bab ini menyajikan beberapa informasi latar belakang tentang setiap jenis bahaya sehingga Anda dapat lebih memahami sifat sebenarnya dari bahaya tersebut. Kesadaran akan bahaya, pengetahuan tentang bab ini, dan penerapan akal sehat membuat Anda tetap hidup. <br>" +
                "<p align=\"center\"><b>SERANGAN NUKLIR</b><br>" +
                "<p align=\"justify\">Persiapkan diri Anda untuk bertahan dari serangan nuklir dan mengetahui bagaimana bereaksi terhadap bahaya nuklir.<br>" +
                "<br><b>Efek Senjata Nuklir</b><br>" +
                "Efek dari senjata nuklir diklasifikasikan sebagai awal atau residu. Efek awal terjadi di daerah langsung ledakan dan berbahaya pada menit pertama setelah ledakan. Efek sisa bisa bertahan berhari-hari atau bertahun-tahun dan menyebabkan kematian. Efek awal utamanya adalah ledakan dan radiasi.<br>" +
                " <br><b>Ledakan</b><br>" +
                "Ditetapkan sebagai gerakan singkat dan cepat udara jauh dari pusat ledakan dan tekanan yang menyertai gerakan ini. Angin kencang mengiringi ledakan tersebut. Ledakan menghantam puing dan personil, meruntuhkan paru-paru, merusak gendang telinga, struktur dan posisi yang runtuh, dan menyebabkan kematian atau cedera segera dengan efeknya yang menghancurkan.<br>" +
                " <br><b>Radiasi Termal</b><br>" +
                "Panas dan radiasi cahaya yang ditimbulkan bola api ledakan nuklir. Radiasi cahaya terdiri dari cahaya tampak dan sinar ultraviolet dan inframerah. Radiasi termal menghasilkan kebakaran yang luas, luka bakar kulit, dan kebutaan.<br>" +
                " <br><b>Radiasi Nuklir</b><br>" +
                "Radiasi nuklir memecah menjadi dua kategori - radiasi awal dan radiasi residual.<br>" +
                "<br>" +
                "Radiasi nuklir awal terdiri dari sinar gamma intens dan neutron yang dihasilkan pada saat pertama setelah ledakan. Radiasi ini menyebabkan kerusakan sel yang luas di seluruh tubuh. Kerusakan radiasi dapat menyebabkan sakit kepala, mual, muntah, diare, dan bahkan kematian, tergantung dosis radiasi yang diterima. Masalah utama dalam melindungi diri terhadap efek radiasi awal adalah Anda mungkin telah menerima dosis mematikan atau tidak mampu sebelum melakukan tindakan protektif. Personil yang terpapar radiasi mematikan mungkin telah terbunuh atau terluka parah akibat ledakan atau radiasi termal.<br>" +
                "<br>Radiasi sisa terdiri dari semua radiasi yang dihasilkan setelah satu menit dari ledakan. Ini memiliki efek lebih pada Anda daripada radiasi awal. Pembahasan tentang radiasi sisa terjadi dalam paragraf berikutnya.<br>" +
                "<b>Jenis – Jenis Ledakan Nuklir</b><br>" +
                "Ada tiga jenis ledakan nuklir - airburst, burst permukaan, dan ledakan bawah permukaan. Jenis ledakan secara langsung mempengaruhi peluang bertahan hidup Anda. Sebuah ledakan bawah permukaan terjadi sepenuhnya di bawah tanah atau di bawah air. Efeknya tetap berada di bawah permukaan atau di daerah langsung dimana permukaannya runtuh ke kawah di atas lokasi ledakan. Ledakan di bawah permukaan menyebabkan Anda sedikit atau tidak memiliki bahaya radioaktif kecuali Anda memasuki area langsung kawah. Tidak ada diskusi lebih lanjut tentang jenis ledakan ini yang akan terjadi.<br>" +
                "<br>" +
                "Airburst terjadi di udara di atas target yang dituju. Airburst memberikan efek radiasi maksimum pada target dan oleh karena itu sangat berbahaya bagi Anda sehubungan dengan efek nuklir langsung.<br>" +
                "<br>" +
                "Sebuah ledakan permukaan terjadi di permukaan tanah atau air. Banyak hasil kejatuhan, dengan efek jangka panjang yang serius untuk Anda. Jenis ledakan ini adalah bahaya nuklir terbesar Anda.<br>" +
                " <br><b>Kerusakan Nuklir</b><br>" +
                "Sebagian besar cedera di lingkungan nuklir diakibatkan oleh efek nuklir awal dari peledakan tersebut. Cedera ini digolongkan sebagai luka ledakan, thermal, atau radiasi. Cedera radiasi lebih lanjut dapat terjadi jika Anda tidak melakukan tindakan pencegahan yang tepat terhadap kejatuhan. Individu di daerah dekat ledakan nuklir mungkin akan menderita kombinasi dari ketiga jenis cedera tersebut.<br>" +
                " <br><b><i>Kerusakan Dari Ledakan</i></b><br>" +
                "Contoh. Di pelukan ini. Cedera ini digolongkan sebagai luka ledakan, thermal, atau radiasi. Cedera radiasi lebih lanjut bisa terjadi jika anda tidak melakukan tindakan pencegahan yang tepat terhadap kejatuhan. Individu di daerah dekat ledakan nuklir mungkin akan menderita kombinasi dari ketiga jenis ini.<br>" +
                " <br><b><i>Kerusakan Dari Termal</i></b> <br>" +
                "Panas dan cahaya yang dihasilkan bola api nuklir menyebabkan luka panas. Luka bakar pertama, kedua, atau ketiga bisa terjadi. Kebutaan flash juga terjadi. Kebutaan ini mungkin bersifat permanen atau sementara tergantung pada tingkat paparan mata. Penutup substansial dan jarak dari ledakan dapat mencegah cedera termal. Pakaian akan memberikan perlindungan yang signifikan terhadap cedera termal. Tutupi banyak kulit secerah mungkin sebelum ledakan nuklir. Pertolongan pertama untuk luka termal sama dengan pertolongan pertama untuk luka bakar. Tutup luka bakar terbuka (kedua atau ketiga) untuk mencegah masuknya partikel radioaktif. Cuci semua luka bakar sebelum ditutup.<br>" +
                " <br><b><i>Kerusakan Dari Radiasi</i></b><br>" +
                "Neutron, radiasi gamma, radiasi alfa, dan radiasi beta menyebabkan cedera radiasi. Neutron adalah partikel berkecepatan tinggi dan sangat menembus yang benar-benar menghancurkan sel-sel di dalam tubuh Anda. Radiasi gamma mirip dengan sinar X dan juga merupakan radiasi yang sangat tajam. Selama tahap awal bola api dari peledakan nuklir, radiasi gamma awal dan neutron adalah ancaman paling serius. Radiasi beta dan alpha adalah partikel radioaktif yang biasanya terkait dengan debu radioaktif akibat kejatuhan. Mereka adalah partikel jarak pendek dan Anda dapat dengan mudah melindungi diri dari bahaya jika Anda melakukan tindakan pencegahan. Lihat Reaksi Tubuh terhadap Radiasi, di bawah, untuk gejala cedera radiasi.<br>" +
                " <br><b><i>Sisa Radiasi</b></i><br>" +
                "Radiasi sisa adalah radiasi yang dipancarkan setelah 1 menit dari saat ledakan nuklir. Radiasi sisa terdiri dari radiasi dan kejenuhan yang diinduksi.<br>" +
                " <br><b><i>Terinduksi Radiasi</i></b><br>" +
                "Radiasi sisa adalah radiasi yang dipancarkan setelah 1 menit dari saat ledakan nuklir. Radiasi sisa dari radiasi dan kejenuhan yang diinduksi.<br>" +
                " <br><b><i>Fallout</i></b> <br>" +
                "Fallout terdiri dari partikel radioaktif tanah dan air, serta fragmen senjata. Selama ledakan permukaan, atau jika bola api nuklir di udara menyentuh tanah, sejumlah besar tanah dan air menguap bersamaan dengan fragmen bom tersebut, dan dipaksa naik ke ketinggian 25.000 meter atau lebih. Bila kandungan menguap ini dingin, mereka dapat membentuk lebih dari 200 produk radioaktif yang berbeda. Isi bom menguap mengembun menjadi partikel radioaktif kecil yang dibawa angin dan mereka kembali ke bumi sebagai debu radioaktif. Partikel Fallout memancarkan radiasi alfa, beta, dan gamma. Radiasi alfa dan beta relatif mudah untuk melawan, dan radiasi gamma residu jauh lebih tidak intens daripada radiasi gamma yang dipancarkan pada menit pertama setelah ledakan. Fallout adalah bahaya radiasi Anda yang paling signifikan, asalkan Anda belum menerima dosis radiasi mematikan dari radiasi awal.<br>" +
                " <br><b>Reaksi Tubuh Terhadap Radiasi</b><br>" +
                "Efek radiasi pada tubuh manusia dapat diklasifikasikan secara luas baik kronis maupun akut. Efek kronis adalah yang terjadi beberapa tahun setelah terpapar radiasi. Contohnya adalah kanker dan cacat genetik. Efek kronis adalah perhatian kecil sejauh mempengaruhi kelangsungan hidup langsung Anda di lingkungan radioaktif. Di sisi lain, efek akut sangat penting bagi kelangsungan hidup Anda. Beberapa efek akut terjadi beberapa jam setelah terpapar radiasi. Efek ini diakibatkan oleh kerusakan fisik langsung radiasi pada jaringan. Penyakit radiasi dan luka bakar beta adalah contoh efek akut. Gejala penyakit radiasi meliputi mual, diare, muntah, kelelahan, kelemahan, dan hilangnya rambut. Penetrasi sinar beta menyebabkan luka bakar; luka itu mirip dengan luka bakar.<br>" +
                " <br><b><i>Kemampuan Pemulihan</i> </b><br>" +
                "Tingkat kerusakan tubuh terutama bergantung pada bagian tubuh yang terpapar radiasi dan berapa lama terpapar, serta kemampuannya untuk pulih. Otak dan ginjal memiliki sedikit kemampuan untuk sembuh. Bagian lain (kulit dan sumsum tulang) memiliki kemampuan yang besar untuk pulih dari kerusakan. Biasanya, dosis 600 centigrams (cgys) ke seluruh tubuh akan mengakibatkan kematian hampir pasti. Jika saja tangan Anda menerima dosis yang sama ini, kesehatan Anda secara keseluruhan tidak akan banyak menderita, walaupun tangan Anda akan mengalami kerusakan parah.<br>" +
                " <br><b><i>Bahaya Eksternal dan Internal </i></b><br>" +
                "Bahaya eksternal atau internal dapat menyebabkan kerusakan pada tubuh. Radiasi gamma yang sangat tembus atau radiasi beta yang kurang tembus yang menyebabkan luka bakar dapat menyebabkan kerusakan eksternal. Masuknya partikel pemancar radiasi alpha atau beta ke dalam tubuh dapat menyebabkan kerusakan internal. Bahaya eksternal menghasilkan radiasi iradiasi dan beta secara keseluruhan. Bahaya internal menyebabkan penyinaran organ penting seperti saluran pencernaan, kelenjar tiroid, dan tulang. Sejumlah kecil bahan radioaktif dapat menyebabkan kerusakan parah pada organ dalam ini dan organ dalam lainnya. Bahaya internal dapat masuk ke dalam tubuh melalui konsumsi air atau makanan yang terkontaminasi atau melalui penyerapan melalui luka atau lecet. Bahan yang masuk ke tubuh melalui pernapasan hanya menimbulkan sedikit bahaya. Anda dapat sangat mengurangi bahaya radiasi internal dengan menggunakan kebersihan pribadi yang baik dan dengan hati-hati mendekontaminasi makanan dan air Anda.<br>" +
                " <br><b><i>Gejala</i></b><br>" +
                "Gejala luka radiasi meliputi mual, diare, dan muntah. Tingkat keparahan gejala ini adalah karena sensitivitas ekstrim saluran cerna terhadap radiasi. Tingkat keparahan gejala dan kecepatan onset setelah terpapar adalah indikator bagus tingkat kerusakan radiasi. Kerusakan gastrointestinal bisa berasal dari bahaya radiasi eksternal atau internal.<br>" +
                " <br><b><i>Penanggulangan Penetrasi Radiasi Eksternal</i></b><br>" +
                "Pengetahuan tentang bahaya radiasi yang dibahas sebelumnya sangat penting untuk bertahan di daerah yang tidak sesuai. Hal ini juga penting untuk mengetahui bagaimana melindungi diri dari radiasi radiasi radiasi tembus radiasi yang paling berbahaya.<br><br>" +
                "<br>" +
                "Cara yang bisa Anda gunakan untuk melindungi diri dari penetrasi radiasi eksternal adalah waktu, jarak, dan perisai. Anda dapat mengurangi tingkat radiasi dan membantu meningkatkan kesempatan bertahan hidup dengan mengendalikan durasi pemaparan. Anda juga bisa mendapatkan sejauh mungkin dari sumber radiasi. Akhirnya Anda dapat menempatkan beberapa bahan penyerap radiasi atau pelindung antara Anda dan radiasi.<br>" +
                " <br><b>Waktu</b> <br>" +
                "Waktunya penting bagi Anda, sebagai survivor, dengan dua cara. Pertama, dosis radiasi bersifat kumulatif. Semakin lama Anda terkena sumber radioaktif, semakin besar dosis yang akan Anda terima. Jelas, habiskan sedikit waktu di area radioaktif sebanyak mungkin. Kedua, radioaktivitas menurun atau meluruh seiring berjalannya waktu. Konsep ini dikenal sebagai paruh radioaktif. Dengan demikian, elemen radioaktif meluruh atau kehilangan separuh radioaktivitasnya dalam waktu tertentu. Aturan praktis untuk peluruhan radioaktif adalah penurunan intensitas dengan faktor sepuluh untuk setiap kenaikan tujuh kali lipat seiring dengan tingkat radiasi puncak. Misalnya, jika area kejatuhan nuklir memiliki tingkat radiasi maksimum 200 cgys per jam saat kejatuhannya selesai, tingkat ini akan turun menjadi 20 cgys per jam setelah 7 jam; itu akan jatuh lebih jauh ke 2 cgys per jam setelah 49 jam. Bahkan pengamat yang tidak terlatih dapat melihat bahwa bahaya terbesar akibat kejatuhan terjadi segera setelah peledakan, dan bahayanya berkurang dengan cepat dalam waktu yang relatif singkat. Sebagai survivor, cobalah untuk menghindari kejatuhan daerah sampai radioaktif meluruh ke tingkat yang aman. Jika Anda dapat menghindari area yang tidak stabil cukup lama sehingga sebagian besar radioaktivitas dapat membusuk, Anda meningkatkan kesempatan bertahan hidup.<br>" +
                " <b><br>Jarak</b><br>" +
                "Jarak memberikan perlindungan yang sangat efektif terhadap radiasi gamma penetrasi karena intensitas radiasi berkurang dengan kuadrat jarak dari sumbernya. Misalnya, jika terkena 1.000 cgys radiasi berdiri 30 sentimeter dari sumbernya, pada 60 sentimeter, Anda hanya akan menerima 250 cgys. Jadi, bila Anda melipatgandakan jarak, radiasi akan menurun menjadi (0,5) 2 atau 0,25 jumlahnya. Sementara formula ini berlaku untuk sumber radiasi terkonsentrasi di daerah kecil, ini menjadi lebih rumit untuk area radiasi yang luas seperti daerah yang rusak.<br>" +
                " <br><b>Perlindungan</b><br>" +
                "Jarak yang sangat efektif terhadap radiasi gamma penetrasi karena intensitas reduksi dengan kuadrat jarak dari sumbernya. Misalnya, jika terkena 1.000 cgys radiasi berdiri 30 sentimeter dari sumbernya, pada 60 sentimeter, Anda hanya akan menerima 250 cgys. Jadi, bila Anda melipatgandakan jarak, maka akan menurun menjadi (0,5) 2 atau 0,25 gag. Sementara rumus ini berlaku untuk sumber radiasi terkonsentrasi di daerah kecil, ini menjadi lebih rumit untuk area radiasi yang luas seperti daerah yang rusak.<br>" +
                " <br><b>Aspek Medis Khusus</b><br>" +
                "Kehadiran materi kejatuhan di daerah Anda memerlukan sedikit perubahan dalam prosedur pertolongan pertama. Anda harus menutupi semua luka untuk mencegah kontaminasi dan masuknya partikel radioaktif. Anda harus terlebih dulu mencuci luka bakar radiasi beta, lalu memperlakukannya sebagai luka bakar biasa. Ambil tindakan ekstra untuk mencegah infeksi. Tubuh Anda akan sangat sensitif terhadap infeksi akibat perubahan kimia darah Anda. Perhatikan pencegahan flu atau infeksi pernafasan. Mengurangi kebersihan diri secara ketat untuk mencegah infeksi. Tutupi mata Anda dengan kacamata improvisasi untuk mencegah masuknya partikel.<br>" +
                " <br><b>Tempat Perlindugan</b><br>" +
                "Seperti yang dinyatakan sebelumnya, efektivitas bahan perisai bergantung pada ketebalan dan densitasnya. Ketebalan bahan pelindung yang cukup akan mengurangi tingkat radiasi menjadi jumlah yang dapat diabaikan.<br>" +
                "Alasan utama untuk menemukan dan membangun tempat berlindung adalah untuk mendapatkan perlindungan terhadap tingkat radiasi intensitas kejenuhan gamma dini secepat mungkin. Lima menit untuk mencari tempat penampungan adalah panduan yang bagus. Kecepatan dalam mencari tempat berlindung sangat penting. Tanpa tempat berlindung, dosis yang diterima dalam beberapa jam pertama akan melebihi yang diterima selama sisa minggu di daerah yang terkontaminasi. Dosis yang diterima di minggu pertama ini akan melebihi dosis yang terakumulasi selama sisa masa pakai di area yang terkontaminasi.<br>" +
                " <br><b><i>Material Perlindungan</i></b><br>" +
                "Ketebalan yang dibutuhkan untuk melemahkan radiasi gamma dari kejatuhan jauh lebih kecil dari yang dibutuhkan untuk melindungi terhadap radiasi gamma awal. Radiasi kejut memiliki sedikit energi daripada radiasi awal peledakan nuklir. Untuk radiasi kejatuhan, sejumlah kecil bahan pelindung dapat memberikan perlindungan yang memadai. Gambar 23-1 memberi gambaran tentang ketebalan berbagai bahan yang dibutuhkan untuk mengurangi transmisi radiasi gamma sisa sebesar 50 persen.<br>" +
                " <br>";
        String text2 =
                "Prinsip ketebalan lapisan half-value berguna dalam memahami penyerapan radiasi gamma dengan berbagai bahan. Menurut prinsip ini, jika batu bata 5 sentimeter mengurangi tingkat radiasi gamma hingga satu setengah, tambahkan satu batu bata 5 sentimeter lagi (lapisan setengah nilai lainnya) akan mengurangi intensitas setengah lainnya, yaitu seperempat jumlah aslinya. . Lima belas sentimeter akan mengurangi tingkat kejatuhan radiasi gamma menjadi seperdelapan jumlah aslinya, 20 sentimeter sampai seperenam, dan seterusnya. Dengan demikian, tempat penampungan yang dilindungi oleh 1 meter kotoran akan mengurangi intensitas radiasi 1.000 cgys per jam di luar hingga sekitar 0,5 cgy per jam di dalam tempat penampungan.<br>" +
                " <br><b><i>Tempat Perlindungan Alami</i></b><br>" +
                "Medan yang menyediakan perisai alami dan konstruksi tempat penampungan yang mudah adalah lokasi yang ideal untuk tempat penampungan darurat. Contoh bagus adalah selokan, jurang, tebing berbatu, bukit, dan tepian sungai. Di daerah tingkat tanpa perlindungan alami, gali posisi bertarung atau parit celah.<br>" +
                " <br><b><i>Parit</i></b> <br>" +
                "Medan yang menyediakan perisai alami dan bangunan tempat penampungan yang mudah adalah lokasi yang ideal untuk tempat penampungan darurat. Contoh bagusnya adalah selokan, jurang, tebing berbatu, bukit, dan tepian sungai. Di daerah tingkat tidak sehat, gali posisi bertarung atau parit.<br>" +
                " <br><b>Tempat Perlindungan Lainnya</i></b><br>" +
                "Sementara tempat penampungan bawah tanah yang ditutupi oleh 1 meter atau lebih bumi memberikan perlindungan terbaik terhadap radiasi kejatuhan, struktur kosong berikut (sesuai urutannya) menawarkan perlindungan terbaik berikutnya:<br>" +
                "<ul><li>Gua dan terowongan ditutupi oleh lebih dari 1 meter tanah.</li>" +
                "<li>Ruang penyimpanan badai atau gudang penyimpanan.</li>" +
                "<li>Gorong-gorong</li>" +
                "<li>Ruang bawah tanah atau gudang bangunan terbengkalai.</li>" +
                "<li>Bangunan terbengkalai terbuat dari batu atau lumpur.</li>" +
                "</ul><b><i>Atap </i></b><br>" +
                "Tidak wajib bahwa Anda membangun atap di tempat penampungan Anda. Buat satu hanya jika bahannya mudah didapat hanya dengan paparan singkat terhadap kontaminasi luar. Jika membangun atap memerlukan pemaparan radiasi penetrasi yang meluas, akan lebih bijaksana untuk meninggalkan tempat penampungan tanpa atap. Fungsi satu atap adalah mengurangi radiasi dari sumber kejatuhan ke tubuh Anda. Kecuali Anda menggunakan atap yang tebal, atapnya sangat sedikit melindungi.<br>" +
                " <br>Anda bisa membuat atap sederhana dari poncho yang dilubangi dengan tanah, batu, atau sampah lainnya dari tempat penampungan Anda. Anda dapat membuang sebagian besar kotoran dan kotoran dari bagian atas poncho dengan memukulinya dari dalam pada interval yang sering. Penutup ini tidak akan menawarkan perisai dari partikel radioaktif yang diletakkan di permukaan, namun akan meningkatkan jarak dari sumber kejatuhan dan menjaga area penampungan dari kontaminasi lebih lanjut.Seleksi Lokasi Tempat Tinggal dan Persiapan<br>" +
                " <br>Untuk mengurangi waktu pemaparan Anda dan dengan demikian mengurangi dosis yang diterima, ingat faktor berikut saat memilih dan menyiapkan tempat penampungan:<br>" +
                "<ul><li>Bila memungkinkan, carilah tempat penampungan yang baru dan mentah yang dapat Anda tingkatkan. Jika tidak ada yang tersedia, gali parit.</li>" +
                "<li><p align=\"justify\">Gali tempat berlindung yang cukup dalam untuk mendapatkan perlindungan yang baik, lalu perbesar seperti yang dibutuhkan untuk kenyamanan.</li>" +
                "<li><p align=\"justify\">Tutup bagian atas posisi bertarung atau parit dengan bahan yang tersedia dan lapisan bumi yang tebal, jika Anda bisa melakukannya tanpa meninggalkan tempat penampungan. Sementara atap dan kamuflase sama-sama diinginkan, mungkin lebih aman untuk dilakukan tanpa mereka daripada mengekspos diri Anda pada radiasi di luar posisi pertempuran Anda.</li>" +
                "<li><p align=\"justify\">Saat membangun tempat penampungan Anda, jaga agar seluruh bagian tubuh Anda ditutupi pakaian untuk melindunginya dari luka bakar beta.</li>" +
                "<li><p align=\"justify\">Bersihkan tempat berlindung dari deposit permukaan apapun dengan menggunakan cabang atau benda lain yang dapat Anda buang. Lakukan pembersihan ini untuk menghilangkan bahan yang terkontaminasi dari area yang akan Anda tempati. Area yang dibersihkan harus meluas setidaknya 1,5 meter di luar area tempat penampungan Anda.</li>" +
                "<li><p align=\"justify\">Dekontaminasi bahan yang Anda bawa ke tempat penampungan. Bahan ini termasuk rumput atau dedaunan yang Anda gunakan sebagai insulasi atau tempat tidur, dan pakaian luar Anda (terutama alas kaki). Jika cuaca memungkinkan dan Anda memiliki pakaian luar yang sangat terkontaminasi, Anda mungkin ingin melepaskannya dan menguburnya di bawah kaki bumi di ujung tempat penampungan Anda. Anda mungkin mengambilnya nanti (setelah peluruhan radioaktif) saat meninggalkan tempat penampungan. Jika pakaian itu kering, Anda bisa mendekontaminasinya dengan cara memukul atau menggoyangnya di luar pintu masuk tempat penampungan untuk menghilangkan debu radioaktif. Anda dapat menggunakan badan air, meskipun terkontaminasi, untuk menghilangkan bahan-bahan dari partikel-partikel kejatuhan yang berlebihan. Cukup celupkan bahan ke dalam air dan kocok untuk menyingkirkan kelebihan air. Jangan memerasnya, tindakan ini akan menjebak partikel.</li>" +
                "<li><p align=\"justify\">Jika memungkinkan dan tanpa meninggalkan tempat penampungan, cuci bersih tubuh Anda dengan sabun dan air, bahkan jika air di tangan bisa terkontaminasi. Pencucian ini akan menghilangkan sebagian besar partikel radioaktif berbahaya yang cenderung menyebabkan luka bakar beta atau kerusakan lainnya. Jika air tidak tersedia, bersihkan wajah dan permukaan kulit yang terpapar lainnya untuk menghilangkan debu dan kotoran yang terkontaminasi. Anda bisa menyeka wajah Anda dengan sehelai kain bersih atau segenggam kotoran yang tidak terkontaminasi. Anda mendapatkan kotoran yang tidak terkontaminasi ini dengan mengikis beberapa inci tanah teratas dan menggunakan kotoran \"bersih\".</li>" +
                "<li><p align=\"justify\">Setelah menyelesaikan tempat penampungan, berbaring, tetap hangat, dan tidur dan istirahat semaksimal mungkin saat berada di tempat penampungan.</li>" +
                "<li><p align=\"justify\">Bila tidak beristirahat, tetap sibuk dengan merencanakan tindakan di masa depan, mempelajari peta Anda, atau membuat tempat berteduh lebih nyaman dan efektif.</li>" +
                "<li><p align=\"justify\">Jangan panik jika Anda mengalami mual dan gejala penyakit radiasi. Bahaya utama Anda dari penyakit radiasi adalah infeksi. Tidak ada pertolongan pertama untuk penyakit ini. Beristirahat, minum cairan, minum obat apapun yang mencegah muntah, menjaga asupan makanan Anda, dan mencegah pemaparan tambahan akan membantu menghindari infeksi dan pemulihan bantuan. Bahkan dosis radiasi yang kecil pun bisa menyebabkan gejala ini yang bisa hilang dalam waktu singkat.</li>" +
                "</ul><b><i>Waktu Pemaparan</i></b><br>" +
                "<p align=\"justify\">Jadwal berikut memberi Anda informasi yang dibutuhkan untuk menghindari menerima dosis serius dan tetap membiarkan Anda mengatasi masalah kelangsungan hidup:<br>" +
                "<ul><li>Isolasi lengkap dari 4 sampai 6 hari setelah pengiriman senjata terakhir.</li>" +
                "<li>Paparan yang sangat singkat untuk mendapatkan air pada hari ketiga diperbolehkan, namun pemaparan tidak boleh melebihi 30 menit.</li>" +
                "<li>Satu pemaparan tidak lebih dari 30 menit pada hari ketujuh.</li>" +
                "<li>Satu pemaparan tidak lebih dari 1 jam pada hari kedelapan.</li>" +
                "<li>Paparan 2 sampai 4 jam dari hari kesembilan sampai hari keduabelas.</li>" +
                "<li>Operasi normal, diikuti istirahat di tempat perlindungan yang dilindungi, mulai hari ketiga bela</li>" +
                "<li>Dalam semua kasus, buat eksposur Anda sesingkat mungkin. Pertimbangkan hanya persyaratan wajib sebagai alasan pemaparan yang valid. Dekontaminasi di setiap pemberhentian.</li>" +
                "</ul><br>" +
                "<p align=\"justify\">Waktu yang diberikan di atas bersifat konservatif. Jika dipaksa untuk bergerak setelah hari pertama atau kedua, Anda dapat melakukannya, Pastikan bahwa pemaparan tidak lebih dari yang benar-benar diperlukan.<br>" +
                " <br><b>Pengadaan Air</b><br>" +
                "Di daerah yang terkontaminasi, sumber air yang tersedia mungkin terkontaminasi. Jika Anda menunggu setidaknya 48 jam sebelum meminum air untuk memungkinkan peluruhan radioaktif berlangsung dan pilih sumber air yang paling aman, Anda akan sangat mengurangi bahaya menelan sejumlah radioaktivitas berbahaya.<br>" +
                "Meski banyak faktor (arah angin, curah hujan, sedimen) akan mempengaruhi pilihan Anda dalam memilih sumber air, perhatikan panduan berikut.<br>" +
                " <br><b><i>Sumber Air Yang Aman</i></b><br>" +
                "Air dari mata air, sumur, atau sumber bawah tanah lainnya yang mengalami penyaringan alami akan menjadi sumber teraman Anda. Setiap air yang ditemukan di dalam pipa atau wadah rumah atau toko yang ditinggalkan juga terbebas dari partikel radioaktif. Air ini akan aman untuk diminum, meski harus melakukan tindakan pencegahan terhadap bakteri di air.<br>" +
                "<br></b>" +
                "Salju yang diambil dari 15 atau lebih sentimeter di bawah permukaan selama kejatuhan juga merupakan sumber air yang aman.<br>" +
                " <br><b><i>Sungai</i></b><br>" +
                "Air dari sungai dan sungai akan relatif bebas dari kejatuhan dalam beberapa hari setelah ledakan nuklir terakhir karena pengenceran. Jika memungkinkan, saring air tersebut sebelum minum untuk menyingkirkan partikel radioaktif. Metode filtrasi terbaik adalah dengan menggali lubang sedimen atau cekungan rembesan di sepanjang sisi sumber air. Air akan meresap ke lateral ke dalam lubang melalui tanah campur tangan yang bertindak sebagai agen penyaringan dan menghilangkan partikel kejatuhan yang terkontaminasi yang menetap di badan asli air. Metode ini dapat menghilangkan hingga 99 persen radioaktivitas dalam air. Anda harus menutup lubang dengan cara tertentu untuk mencegah kontaminasi lebih lanjut. Lihat Gambar 6-9 untuk contoh saringan air.<br>" +
                " <br><b><i>Genangan Air</i></b><br>" +
                "Air dari danau, kolam, kolam, dan sumber berdiri lainnya kemungkinan akan sangat terkontaminasi, meskipun sebagian besar isotop radioaktif berumur panjang yang lebih berat akan menetap di bagian bawah. Gunakan teknik pengendapan untuk memurnikan air ini. Pertama, isi ember atau wadah dalam lainnya tiga pertiga penuh dengan air yang terkontaminasi. Kemudian ambil kotoran dari kedalaman 10 atau lebih sentimeter di bawah permukaan tanah dan aduk ke dalam air. Gunakan sekitar 2,5 cm kotoran untuk setiap 10 sentimeter air. Aduk air sampai Anda melihat sebagian besar partikel kotoran tersuspensi di dalam air. Biarkan campuran diendapkan minimal 6 jam. Partikel kotoran pengendapan akan membawa sebagian besar partikel jatuh tersendat ke bagian bawah dan menutupinya. Anda kemudian bisa mencelupkan air jernih. Purifikasi air ini menggunakan perangkat filtrasi.<br>" +
                " <br><b><i>Tindakan Pecegahan Tambahan</i></b><br>" +
                "Sebagai tindakan pencegahan tambahan terhadap penyakit, obati semua air dengan tablet pemurni air dari alat bertahan hidup Anda atau rebus.<br>" +
                " <br><b>Pangadaan Makanan</b><br>" +
                "Although it is a serious problem to obtain edible food in a radiation-contaminated area, it is not tidak mungkin untuk dipecahkan Anda perlu mengikuti beberapa prosedur khusus dalam memilih dan menyiapkan jatah dan makanan lokal untuk digunakan. Karena kemasan aman melindungi jatah tempur Anda, mereka akan sangat aman untuk digunakan. Tambahan jatah Anda dengan makanan yang bisa Anda temukan saat bepergian ke luar tempat penampungan Anda. Sebagian besar makanan olahan yang mungkin Anda temukan di bangunan terbengkalai aman digunakan setelah dekontaminasi mereka. Ini termasuk makanan kaleng dan kemasan setelah mengeluarkan wadah atau bungkusnya atau mencuci mereka bebas dari partikel yang tidak rata. Makanan olahan ini juga termasuk makanan yang disimpan dalam wadah tertutup dan makanan yang disimpan di kawasan lindung (seperti gudang bawah tanah), jika Anda mencuci mereka sebelum makan. Cuci semua wadah makanan atau bungkusnya sebelum menangani mereka untuk mencegah kontaminasi lebih lanjut.<br>" +
                "<br>" +
                "Jika sedikit atau tidak ada makanan olahan tersedia di daerah Anda, Anda mungkin harus melengkapi makanan Anda dengan sumber makanan lokal. Sumber makanan lokal adalah hewan dan tumbuhan.<br>" +
                " <br><b><i>Hewan Sebagai Sumber Makanan</i> </b><br>" +
                "Asumsikan bahwa semua hewan, terlepas dari habitat atau kondisi kehidupan mereka, terkena radiasi. Efek radiasi pada hewan sama dengan yang terjadi pada manusia. Dengan demikian, sebagian besar hewan liar yang tinggal di wilayah kejatuhan cenderung menjadi sakit atau meninggal akibat radiasi selama bulan pertama setelah ledakan nuklir. Meskipun hewan mungkin tidak terbebas dari bahan radioaktif berbahaya, Anda dapat dan harus menggunakannya dalam kondisi bertahan hidup sebagai sumber makanan jika makanan lain tidak tersedia. Dengan persiapan yang matang dan dengan mengikuti beberapa prinsip penting, hewan dapat menjadi sumber makanan yang aman.<br>" +
                "<br>" +
                "Pertama, jangan makan binatang yang nampaknya sakit. Ini mungkin telah mengembangkan infeksi bakteri akibat keracunan radiasi. Daging yang terkontaminasi, meski sudah matang, bisa menyebabkan penyakit parah atau kematian jika dimakan.<br>" +
                "<br>"+
                "Hati-hati kulit semua hewan untuk mencegah partikel radioaktif pada kulit atau bulu memasuki tubuh. Jangan makan daging yang dekat dengan tulang dan persendian karena kerangka hewan mengandung lebih dari 90 persen radioaktivitas. Jaringan otot hewan yang tersisa, bagaimanapun, akan aman dikonsumsi. Sebelum memasak, potong daging dari tulang, biarkan setidaknya 3 milimeter ketebalan daging di tulang. Buang semua organ dalam (hati, hati, dan ginjal) karena mereka cenderung mengkonsentrasikan radioaktivitas beta dan gamma.<br>" +
                "<br>" +
                "Masak semua daging sampai sangat baik dilakukan. Untuk memastikan dagingnya matang, potong menjadi potongan kurang dari 13 milimeter sebelum dimasak. Pemotongan tersebut juga akan mengurangi waktu memasak dan menghemat bahan bakar.<br>" +
                " <br>Luasnya kontaminasi pada ikan dan hewan air akan jauh lebih besar daripada hewan darat. Hal ini juga berlaku untuk tanaman air, terutama di daerah pesisir. Gunakan sumber makanan akuatik hanya dalam kondisi darurat ekstrim.<br>" +
                "Semua telur, meski dibaringkan selama periode kejatuhan, akan aman dikonsumsi. Sepenuhnya menghindari susu dari binatang manapun di daerah yang tidak stabil karena hewan menyerap sejumlah besar radioaktivitas dari tanaman yang mereka makan.<br>" +
                " <br><b><i>Tumbuhan Sebagai Sumber Makanan</i></b> <br>" +
                "Kontaminasi tanaman terjadi dengan akumulasi kejatuhan pada permukaan luarnya atau dengan penyerapan unsur radioaktif melalui akarnya. Pilihan pertama Anda dari makanan nabati harus berupa sayuran seperti kentang, lobak, wortel, dan tanaman lainnya yang bagiannya dapat tumbuh di bawah tanah. Ini adalah makanan yang paling aman setelah Anda menggosoknya dan mengeluarkan kulitnya.<br>" +
                "<br>" +
                "Kedua dalam urutan preferensi adalah tanaman dengan bagian yang dapat dimakan yang bisa Anda dekontaminasi dengan mencuci dan mengupas permukaan luarnya. Contohnya adalah pisang, apel, tomat, pir berduri, dan buah dan sayuran lainnya.<br>" +
                "<br>" +
                "Setiap sayuran, buah, atau tanaman berkulit halus yang tidak dapat Anda gosok dengan mudah atau secara efektif didekontaminasi dengan pencucian akan menjadi pilihan ketiga makanan darurat Anda.<br>" +
                "<br>" +
                "Efektivitas dekontaminasi dengan cara menggosok berbanding terbalik dengan kekasaran permukaan buah. Buah dengan permukaan halus telah kehilangan 90 persen kontaminasi mereka setelah dicuci, sambil mencuci tanaman dengan permukaan kasar hanya menghilangkan sekitar 50 persen kontaminasi.<br>" +
                "<br>" +
                "Anda makan tanaman kasar (seperti selada) hanya sebagai upaya terakhir karena Anda tidak dapat secara efektif mendekontaminasinya dengan cara mengupas atau mencuci. Makanan sulit lainnya untuk didekontaminasi dengan mencuci dengan air meliputi buah kering (buah ara, plum, buah persik, aprikot, pir) dan kacang kedelai.<br>" +
                "<br>" +
                "Secara umum, Anda bisa menggunakan makanan nabati yang siap dipanen jika Anda bisa secara efektif mendekontaminasinya. Tanaman yang tumbuh, bagaimanapun, dapat menyerap beberapa bahan radioaktif melalui daun dan juga dari tanah, terutama jika hujan telah terjadi selama atau setelah periode kejatuhan. Hindari menggunakan tanaman ini untuk makanan kecuali dalam keadaan darurat.v" +
                "<p align=\"center\"><b>SERANGAN BIOLOGI</b><br>" +
                "<p align=\"justify\">Penggunaan agen biologi itu nyata. Persiapkan diri Anda untuk bertahan hidup dengan menjadi mahir dalam tugas yang diidentifikasi dalam Manuskrip Praktik Tugas Biasa Anda (SMPS). Tahu apa yang harus dilakukan untuk melindungi diri dari perantara ini. <br>" +
                "Perantara dan Efek Biologis<br>" +
                "Perantara biologis adalah mikroorganisme yang dapat menyebabkan penyakit di antara personil, hewan, atau tumbuhan. Mereka juga bisa menyebabkan kerusakan material. Agen ini terbagi dalam dua kategori besar - patogen (biasanya disebut kuman) dan racun. Patogen adalah mikroorganisme hidup yang menyebabkan penyakit mematikan atau melumpuhkan. Bakteri, rickettsiae, jamur, dan virus termasuk dalam patogen. Racun adalah racun yang diproduksi tanaman, hewan, atau mikroorganisme secara alami. Kemungkinan racun perang biologis yang mungkin mencakup berbagai neurotoksik (mempengaruhi sistem saraf pusat) dan senyawa sitotoksik (menyebabkan kematian sel).<br>" +
                " <br><b><i>Kuman</b></i> <br>" +
                "Kuman adalah organisme hidup. Beberapa negara telah menggunakan mereka di masa lalu sebagai senjata. Hanya sedikit kuman yang bisa memulai infeksi, terutama jika terhirup ke paru-paru. Karena kuman sangat kecil dan beratnya sangat kecil, angin bisa menyebar jarak jauh; mereka juga dapat memasuki tempat yang tidak difilter atau tidak. Bangunan dan bunker bisa menjebaknya sehingga menyebabkan konsentrasi lebih tinggi. Kuman tidak mempengaruhi tubuh dengan segera. Mereka harus berkembang biak di dalam tubuh dan mengatasi pertahanan tubuh - sebuah proses yang disebut masa inkubasi. Masa inkubasi bervariasi dari beberapa jam sampai beberapa bulan, tergantung pada kumannya. Sebagian besar kuman harus hidup dalam organisme hidup lain (host), seperti tubuh Anda, untuk bertahan dan tumbuh. Kondisi cuaca seperti angin, hujan, dingin, dan sinar matahari cepat membunuh kuman.<br>" +
                "<br>" +
                "Beberapa kuman bisa membentuk cangkang pelindung, atau spora, untuk memungkinkan bertahan hidup di luar inang. Agen penghasil spora adalah bahaya jangka panjang yang harus Anda netralkan dengan cara mendekontaminasi daerah atau personil yang terinfeksi. Untungnya, kebanyakan agen hidup tidak menghasilkan spora. Agen ini harus menemukan host dalam kira-kira satu hari pengiriman mereka atau mereka mati. Kuman memiliki tiga rute dasar masuk ke tubuh Anda: melalui saluran pernapasan, melalui jeda di kulit, dan melalui saluran pencernaan. Gejala infeksi bervariasi sesuai dengan penyakit.<br>" +
                " <br><b><i>Racun </b></i><br>" +
                "Racun adalah zat yang tumbuh-tumbuhan, hewan, atau kuman menghasilkan secara alami. Racun ini yang sebenarnya merugikan manusia, bukan bakteri. Botulin, yang memproduksi botulisme, adalah sebuah contoh. Ilmu pengetahuan modern telah memungkinkan produksi racun-racun ini secara besar-besaran tanpa penggunaan kuman yang menghasilkan toksin. Racun dapat menghasilkan efek yang serupa dengan zat kimia. Namun korban yang beracun mungkin tidak menanggapi tindakan pertolongan pertama yang digunakan untuk melawan agen kimia. Racun masuk ke tubuh dengan cara yang sama seperti kuman. Namun, beberapa toksin, tidak seperti kuman, bisa menembus kulit yang tak terputus. Gejala muncul segera, karena tidak ada masa inkubasi. Banyak racun sangat mematikan, meski dalam dosis sangat kecil. Gejala mungkin termasuk salah satu dari berikut ini:<br>" +
                "<ul><li>Pusing.</li>" +
                "<li>Kebingungan mental.</li>" +
                "<li>Penglihatan kabur atau ganda.</li>" +
                "<li>Mati rasa atau kesemutan pada kulit.</li>" +
                "<li>Kelumpuhan.</li>" +
                "<li>Kejang-kejang.</li>" +
                "<li>Ruam atau lecet.</li>" +
                "<li>Batuk.</li>" +
                "<li>Demam.</li>" +
                "<li>Otot sakit.</li>" +
                "<li>Kelelahan.</li>" +
                "<li>Mual, muntah, dan / atau diare.</li>" +
                "<li>Perdarahan dari bukaan badan.</li>" +
                "<li>Darah dalam urin, tinja, atau air liur.</li>" +
                "<li>Kejutan.</li>" +
                "<li>Kematian.</li>" +
                "</ul><b>Pendeteksian</b><br>" +
                "<p align=\"justify\">Agen biologis secara alami sulit dideteksi. Anda tidak dapat mendeteksi mereka dengan salah satu dari lima indra fisik. Seringkali, tanda pertama agen biologis akan menjadi gejala korban yang terpapar agen tersebut. Kesempatan terbaik Anda untuk mendeteksi agen biologis sebelum mereka dapat mempengaruhi Anda adalah dengan mengenali cara pengiriman mereka. Tiga sarana utama pengiriman adalah -<br>" +
                "<ul><li>Munisi tipe-meledak. Ini mungkin bom atau proyektil yang meledak menyebabkan kerusakan yang sangat kecil. Ledakan tersebut akan menghasilkan awan kecil cairan atau bubuk di daerah benturan langsung. Awan ini akhirnya akan menyebar; laju dispersi tergantung pada kondisi medan dan cuaca.</li>" +
                "<li>tangki semprotan atau generator. Tangki pesawat terbang atau kendaraan atau generator aerosol tingkat dasar menghasilkan awan aerosol agen biologis.</li>" +
                "<li>Vektor. Serangga seperti nyamuk, kutu, kutu, dan kutu mengantarkan patogen. Infestasi besar serangga ini mungkin mengindikasikan penggunaan agen biologis.</li>" +
                "</ul><br>" +
                "<p align=\"justify\">Tanda lain dari kemungkinan serangan biologis adalah adanya zat yang tidak biasa di tanah atau di vegetasi, atau tanaman yang tampak sakit, tanaman pangan, atau hewan.<br><br><br><br>" +
                " <br><b>Pengaruh Cuaca dan Medan Lokasi</b><br>" +
                "Pengetahuan Anda tentang bagaimana cuaca dan medan mempengaruhi agen dapat membantu Anda menghindari kontaminasi oleh agen biologis. Faktor cuaca utama yang mempengaruhi agen biologis adalah sinar matahari, angin, dan curah hujan. Semprotan aerosol akan cenderung berkonsentrasi di daerah dataran rendah, mirip dengan kabut pagi hari.<br>" +
                "<br>" +
                "Sinar matahari mengandung radiasi matahari yang tampak dan ultraviolet yang dengan cepat membunuh kebanyakan kuman yang digunakan sebagai agen biologis. Namun, penutup alami atau buatan manusia dapat melindungi beberapa agen dari sinar matahari. Strain kuman buatan manusia lainnya mungkin tahan terhadap sinar matahari.<br>" +
                "<br>" +
                "Kecepatan angin yang tinggi meningkatkan dispersi zat biologis, mencairkan konsentrasinya, dan menyebabkan dehidrasi. Semakin jauh arah yang ditempuh agen, semakin tidak efektif pengenceran dan kematian patogen. Namun, daerah bahaya bahaya dari agen biologis itu penting dan Anda tidak dapat mengabaikannya.<br>" +
                "<br>" +
                "Curah hujan dalam bentuk hujan sedang sampai berat cenderung mencuci agen biologis dari udara, mengurangi daerah bahaya angin sepi. Namun, agen mungkin masih sangat efektif di mana mereka disimpan di lapangan.<br>" +
                " <br><b>Perlindungan</b><br>" +
                "Meskipun Anda harus menjaga rasa hormat yang sehat terhadap agen biologis, tidak ada alasan bagi Anda untuk panik. Anda dapat mengurangi kerentanan Anda terhadap agen biologis dengan mempertahankan imunisasi saat ini, menghindari area yang terkontaminasi, dan mengendalikan tikus dan hama. Anda juga harus menggunakan tindakan pertolongan pertama yang benar dalam penanganan luka dan hanya sumber makanan dan air yang aman dan benar-benar didekontaminasi. Anda harus memastikan bahwa Anda cukup tidur untuk mencegah kondisi run-down. Anda harus selalu menggunakan prosedur sanitasi lapangan yang benar.<br>" +
                "<br>" +
                "Dengan asumsi Anda tidak memiliki masker pelindung, selalu usahakan menutupi wajah dengan beberapa jenis kain untuk melindungi diri dari aerosol agen biologi. Debu mungkin mengandung zat biologis; Pakailah beberapa jenis masker saat debu mengudara.<br>" +
                " <br>Seragam dan sarung tangan Anda akan melindungi Anda dari gigitan dari vektor (nyamuk dan kutu) yang membawa penyakit. Sepenuhnya kancing pakaian Anda dan selipkan celana Anda erat ke sepatu bot Anda. Pakailah pengelupasan pelindung kimiawi, jika tersedia, karena memberikan perlindungan lebih baik daripada pakaian biasa. Meliputi kulit Anda juga akan mengurangi kemungkinan agen memasuki tubuh Anda melalui luka atau goresan. Selalu praktikkan standar kebersihan dan sanitasi pribadi yang tinggi untuk membantu mencegah penyebaran vektor.<br>" +
                "<br>" +
                "Mandi dengan sabun dan air bila memungkinkan. Gunakan sabun kuman pembunuh jika tersedia. Cuci rambut dan tubuh Anda secara menyeluruh, dan bersihkan di bawah kuku jari Anda. Bersihkan gigi, gusi, lidah, dan atap mulut Anda sering. Cuci pakaian Anda dengan air panas bersabun jika bisa. Jika Anda tidak bisa mencuci pakaian Anda, layangkan di area sinar matahari yang terang dan biarkan cahaya membunuh mikroorganisme. Setelah serangan toksin, dekontaminasi diri Anda seolah-olah terkena serangan kimia menggunakan kit M258A2 (jika ada) atau dengan mencuci dengan sabun dan air.<br>" +
                " <br><b>Tempat Perlindungan</b> <br>" +
                "Anda dapat membangun tempat penampungan yang bijaksana di bawah kondisi pencemaran biologis dengan menggunakan teknik yang sama seperti yang dijelaskan di Bab 5. Namun, Anda harus sedikit melakukan perubahan untuk mengurangi kemungkinan kontaminasi biologis. Jangan membangun tempat penampungan Anda dalam depresi di tanah. Semprotan aerosol cenderung berkonsentrasi dalam depresi ini. Hindari membangun tempat berlindung Anda di daerah vegetasi, karena vegetasi memberi keteduhan dan beberapa tingkat perlindungan terhadap agen biologis. Hindari menggunakan vegetasi dalam membangun tempat tinggal Anda. Tempatkan pintu masuk tempat berlindung Anda pada sudut 90 derajat ke angin yang ada. Penempatan tersebut akan membatasi masuknya agen udara dan mencegah stagnasi udara di tempat penampungan Anda. Selalu simpan tempat penampunganmu bersih.<br>" +
                " <br><b>Pengadaan Air</b><br>" +
                "Pengadaan air dalam kondisi biologis sulit tapi bukan tidak mungkin. Bila memungkinkan, coba gunakan air yang sudah terpasang dalam wadah tertutup. Anda bisa berasumsi bahwa air di dalam wadah tertutup tidak terkontaminasi. Cuci wadah air secara saksama dengan sabun dan air atau rebus sekurangnya 10 menit.<br>" +
                "<br>" +
                "Jika air dalam wadah tertutup tidak tersedia, pilihan Anda berikutnya, hanya dalam kondisi darurat, adalah air dari sumber mata air. Sekali lagi, rebus air setidaknya 10 menit sebelum diminum. Jaga agar air tetap tertutup saat merebus untuk mencegah kontaminasi oleh patogen di udara. Pilihan terakhir Anda, hanya dalam keadaan darurat yang ekstrem, adalah dengan menggunakan air berdiri. Vektor dan kuman bisa bertahan dengan mudah di air yang stagnan. Rebus air ini selama praktis membunuh semua organisme. Saring air ini melalui kain untuk melepaskan vektor yang mati. Gunakan tablet pemurni air dalam semua kasus.<br>" +
                " <br><b>Pengadaan Makanan </b><br>" +
                "Pengadaan makanan, seperti pengadaan air, bukan tidak mungkin, tapi Anda harus melakukan tindakan pencegahan khusus. Ransum tempur Anda disegel, dan Anda bisa berasumsi bahwa mereka tidak terkontaminasi. Anda juga bisa berasumsi bahwa wadah tertutup atau paket makanan olahan aman. Untuk memastikan keamanan, dekontaminasi semua wadah makanan dengan mencuci dengan sabun dan air atau dengan merebus wadah dalam air selama 10 menit.<br>" +
                "<br>" +
                "Anda mempertimbangkan untuk melengkapi jatah Anda dengan tanaman lokal atau hewan hanya dalam keadaan darurat yang ekstrem. Tidak peduli apa yang Anda lakukan untuk menyiapkan makanan, tidak ada jaminan bahwa memasak akan membunuh semua agen biologis. Gunakan makanan lokal hanya dalam situasi hidup atau mati. Ingat, Anda bisa bertahan untuk waktu yang lama tanpa makanan, terutama jika makanan yang Anda makan bisa membunuh Anda!<br>" +
                "<br>" +
                "Jika Anda harus menggunakan makanan lokal, pilih saja tanaman dan hewan yang tampak sehat. Jangan memilih pembawa vektor yang diketahui seperti tikus atau hama lainnya. Pilih dan siapkan tanaman seperti di daerah radioaktif. Siapkan hewan seperti tanaman. Selalu gunakan sarung tangan dan pakaian pelindung saat menangani hewan atau tumbuhan. Masak semua makanan tanaman dan hewani dengan cara merebus saja. Rebus semua makanan setidaknya selama 10 menit untuk membunuh semua patogen. Jangan mencoba menggoreng, memanggang, atau memanggang makanan lokal. Tidak ada jaminan bahwa semua bagian yang terinfeksi telah mencapai suhu yang dibutuhkan untuk membunuh semua patogen. Jangan makan makanan mentah.<br>" +
                "<p align=\"center\"><b>SERANGAN KIMIAWI</b><br>" +
                "<p align=\"justify\">Peperangan agen kimia itu nyata. Hal ini dapat menciptakan masalah ekstrim dalam situasi bertahan hidup, namun Anda dapat mengatasi masalah dengan peralatan, pengetahuan, dan pelatihan yang tepat. Sebagai survivor, lini pertahanan pertama Anda melawan agen kimia adalah kemampuan Anda dalam pelatihan nuklir, biologis, dan kimia individual, termasuk memasukkan dan mengenakan masker pelindung dan pengabaian, dekontaminasi pribadi, pengenalan gejala agen kimia, dan individu. pertolongan pertama untuk kontaminasi bahan kimia. SMCT mencakup subjek ini. Jika Anda tidak mahir dalam keterampilan ini, Anda akan memiliki sedikit kesempatan untuk bertahan dalam lingkungan kimia.<br><br>" +
                "<br>" +
                "Materi yang dibahas di bawah ini bukan pengganti tugas individual mana pun yang harus Anda mahir. SMCT menangani berbagai agen kimia, efeknya, dan pertolongan pertama agen ini. Informasi berikut diberikan dengan asumsi Anda ahli dalam menggunakan peralatan pelindung kimia dan mengetahui gejala berbagai agen kimia.<br>" +
                " <br><b>Pendeteksian</b><br>" +
                "Metode terbaik untuk mendeteksi bahan kimia adalah penggunaan detektor zat kimia. Jika sudah memilikinya, gunakanlah. Namun, dalam situasi bertahan hidup, kemungkinan besar Anda hanya harus bergantung pada penggunaan semua indra fisik Anda. Anda harus waspada dan mampu mendeteksi petunjuk yang menunjukkan penggunaan perang kimia. Indikator umum adanya zat kimia adalah air mata, sulit bernapas, tersedak, gatal, batuk, dan pusing. Dengan agen yang sangat sulit dideteksi, Anda harus waspada terhadap gejala pada sesama korban. Lingkungan Anda akan memberikan petunjuk berharga untuk kehadiran agen kimia; misalnya, binatang mati, orang sakit, atau manusia dan hewan yang menampilkan perilaku abnormal.<br>" +
                "<br>" +
                "Rasa penciuman Anda mungkin mengingatkan Anda pada beberapa agen kimia, tapi kebanyakan tidak akan berbau. Bau rumput atau jerami yang baru dipotong bisa mengindikasikan adanya agen tersedak. Bau almond mungkin menunjukkan zat darah.<br>" +
                "<br>" +
                "Penglihatan akan membantu Anda mendeteksi agen kimia. Sebagian besar zat kimia dalam keadaan padat atau cair memiliki beberapa warna. Dingin Dingin Bagi Sikas Bagi Antara sini Dingin Bagi Bagi Bagi Bagi | Bagi Bagi Antara sini Bagi Antara sini Dingin Bagi Bagi Bagi Bagi | Dengan mengamati gejala pada orang lain dan dengan mengamati cara melahirkan, Anda mungkin bisa memiliki beberapa peringatan tentang agen kimia. Gas mustard dalam keadaan cair akan tampak seperti bercak berminyak pada daun atau pada bangunan.<br><br>" +
                " <br>Suara amunisi musuh akan memberi petunjuk adanya senjata kimia. Detak kempa atau peledakan bom adalah indikator yang bagus.<br>" +
                "<br>" +
                "Iritasi di hidung atau mata atau pada kulit merupakan peringatan mendesak untuk melindungi tubuh Anda dari zat kimia. Selain itu, rasa aneh pada makanan, air, atau rokok dapat menjadi peringatan bahwa mereka telah terkontaminasi. <br>" +
                " <br><b>Perlidungan </b><br>" +
                "Sebagai orang yang selamat, selalu gunakan langkah umum berikut, sesuai urutan yang tercantum, untuk melindungi diri dari serangan kimia:<br>" +
                "<ul><li>Gunakan peralatan pelindung.</li>" +
                "<li>Berikan bantuan diri yang cepat dan benar saat terkontaminasi.</li>" +
                "<li>Hindari area dimana agen kimia ada.</li>" +
                "<li>Dekontaminasi peralatan dan tubuh Anda sesegera mungkin.</li>" +
                "</ul><br>" +
                "<p align=\"justify\">Topeng pelindung dan overgarment Anda adalah kunci untuk kelangsungan hidup Anda. Tanpa ini, Anda memiliki kesempatan yang sangat kecil untuk bertahan hidup. Anda harus mengurus barang-barang ini dan melindungi mereka dari kerusakan. Anda harus berlatih dan mengetahui prosedur pertolongan diri yang benar sebelum terpapar agen kimia. Deteksi agen kimia dan penghindaran area yang terkontaminasi sangat penting untuk kelangsungan hidup Anda. Gunakan alat deteksi apa pun yang mungkin tersedia untuk membantu dalam deteksi. Karena Anda berada dalam situasi bertahan hidup, hindari area yang terkontaminasi dengan biaya keseluruhan. Anda bisa mengharapkan bantuan jika Anda terkontaminasi. Jika Anda terkontaminasi, dekontaminasi diri Anda sesegera mungkin dengan menggunakan prosedur yang benar.<br>" +
                " <br><b>Tempat Perlindungan</b><br>" +
                "Jika Anda berada di area yang terkontaminasi, cobalah untuk keluar dari daerah secepat mungkin. Travel crosswind atau melawan angin untuk mengurangi waktu yang dihabiskan di daerah bahaya angin sepi. Jika Anda tidak bisa segera meninggalkan daerah itu dan harus membangun tempat penampungan, gunakan teknik konstruksi tempat penampungan biasa, dengan sedikit perubahan. Bangun tempat penampungan di tempat terbuka, jauh dari semua vegetasi. Hapus semua lapisan atas di area tempat penampungan untuk dekontaminasi daerah tersebut. Jauhkan pintu masuk tempat penampungan tertutup dan berorientasi pada sudut 90 derajat ke angin yang berlaku. Jangan membangun api menggunakan kayu yang terkontaminasi - asapnya akan menjadi racun. Gunakan sangat hati-hati saat memasuki tempat penampungan Anda sehingga Anda tidak akan membawa kontaminasi di dalamnya.<br>" +
                " <br><b>Pengadaan Air </b><br>" +
                "Seperti lingkungan biologis dan nuklir, mendapatkan air di lingkungan kimia sulit dilakukan. Jelas, air dalam wadah tertutup adalah sumber terbaik dan teraman Anda. Anda harus melindungi air ini sebisa mungkin. Pastikan untuk mendekontaminasi kontainer sebelum dibuka.<br>" +
                "Jika Anda tidak bisa mendapatkan air dalam wadah tertutup, cobalah untuk mendapatkannya dari sumber tertutup seperti pipa air bawah tanah. Anda bisa menggunakan air hujan atau salju jika tidak ada bukti kontaminasi. Gunakan air dari sungai yang bergerak lambat, jika perlu, tapi selalu periksa dulu tanda-tanda kontaminasi, dan selalu saring air seperti yang dijelaskan di bawah kondisi nuklir. Tanda-tanda kontaminasi sumber air adalah bau asing seperti bawang putih, mustard, geranium, atau kacang almond pahit; bintik berminyak di permukaan air atau di dekatnya; dan adanya ikan mati atau binatang. Jika tanda-tanda ini ada, jangan gunakan airnya. Selalu rebus atau bersihkan air untuk mencegah infeksi bakteriologis.<br>" +
                " <br><b>Pengadaan Makanan</b> <br>" +
                "Sangat sulit untuk makan sementara di daerah yang terkontaminasi. Anda harus memecah segel pada masker pelindung Anda untuk dimakan. Jika Anda makan, temukan area di mana Anda dapat dengan aman membuka kedok. Sumber makanan paling aman adalah jatah tempur yang disegel. Makanan di kaleng atau botol tertutup juga akan aman. Dekontaminasi semua wadah makanan tertutup sebelum dibuka, jika tidak, anda akan mencemari makanan.<br>" +
                "<br>" +
                "Jika Anda harus melengkapi jatah tempur Anda dengan tanaman atau hewan lokal, jangan gunakan tanaman dari area yang terkontaminasi atau hewan yang tampaknya sedang sakit. Saat menangani tanaman atau hewan, selalu gunakan sarung tangan dan pakaian pelindung.<br>"+
                        "<br><br><i>Departemen Petahanan Amerika Serikat, US Army Field Manual \"Survival\" (FM 21-76), Markas Besar Departemen Tentara Amerika Serikat 1956.";
        String foto1 = "<p align=\"center\"><img src=\"bahaya/bahaya1.png\"></p>";
        String foto2 = "<p align=\"center\"><img src=\"bahaya/bahaya2.png\"></p>";
        String foto3 = "<p align=\"center\"><img src=\"bahaya/bahaya3.png\"></p>";
        view.loadDataWithBaseURL("file:///android_asset/", foto1 + text + foto2 + text2 + foto3 + "</p>", "text/html", "utf-8", null);
        return rootView;
    }

}
